name: 'Discord Notify'
description: 'Send a Discord message to a webhook'
inputs:
  webhook_url:
    description: 'Webhook URL(s) from Discord. if multiple seperate with commas'
    required: true
    default: ''
  title:
    description: 'Title for card. Defaults to PR NUMBER ACTION by USER'
    required: false
    default: ''
  message:
    description: 'Content of card'
    required: false
    default: ''
  include_image:
    description: 'If action is used in a pull request, attach the preview image for it to the card. Required for custom_image_url'
    required: false
    default: true
  avatar_url:
    description: 'Avatar to use for user'
    required: false
    default: ''
  username:
    description: 'Username to send message as'
    required: false
    default: 'GitHub'
  colour:
    description: 'Colour for the edge of the card in hex. Defaults to the usual red/green/purple github colors for actions.'
    required: false
    default: ''
  show_author:
    description: 'Show the author of the action in the card. Defaults to true.'
    required: false
    default: true
  custom_image_url:
    description: 'Include custom image on card, include_image must be true'
    required: false
    default: ''
  title_url:
    description: 'Make the title of the card a link. Sets it to this string.'
    required: false
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'
