name: 'issue-test'
on:
    issues:
        types: ['opened']

jobs:
    test:
         runs-on: ubuntu-latest
         steps:
                - uses: actions/checkout@v6
                - uses: ./
                  with:
                     webhook_url: https://discord.com/api/webhooks/1514217727437307924/Bu_5L1ACFwG0XOCjzNOf4O-dJvr7HKFdFeLByroyOOGHRSVb-23m94S8mqMQrCYBqazn
                     