name: 'test'
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v6
       - name: Setup node
         uses: actions/setup-node@v6
         with:
            node-version: 24.x
       - name: Install dependencies
         run: |
                  npm ci
                  npm ls
       - name: Validate dist
         run: |
              cp dist/main.js main_pr.js
              rm -r dist
              npm install --global rollup
              npm run build
              npm run package
              diff dist/main.js main_pr.js
              if [ $? -ne 0 ]; then
                  echo "Files differ."
                  exit 0
              fi
       - name: discord notify all options
         uses: ./ # Uses an action in the root directory
         with:
            webhook_url: https://test.requestcatcher.com/ # https://requestcatcher.com/ best domain for testing
            title: Test Title
            message: 'Test Message'
            include_image: true
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: TestUsername
            colour: '#3371FF'
            #custom_image_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
