name: 'build-test'
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v6
       - name: Install packages
         run: |
            npm ci
       - name: discord notify all options
         uses: ./ # Uses an action in the root directory
         with:
            webhook_url: https://http-echo-stegzilla.herokuapp.com
            title: Test title
            message: 'test message'
            include_image: true
            avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
            username: TestUsername
            colour: '#3371FF'
            #custom_image_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
